name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install Dep
        run: |
          pip install blind-watermark
      - name: build
        run: |
          curl -o test.jpg https://tu.sioe.cn/gj/qiege/image.jpg
          ls -l
          blind_watermark --embed --pwd 1234 ${{ github.workspace }}/test.jpg "watermark text" ${{ github.workspace }}/embedded.jpg
      - name: test
        run: |
          blind_watermark --extract --pwd 1234 --wm_shape 111 ${{ github.workspace }}/test.jpg

      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: img
          path: ./*.jpg

    